# Structural validation for cmake/openapi_manifest.json.
#
# This stays pure CMake so every normal build and consumer can verify the
# checked-in inventory without Python, a YAML parser, or network access.  The
# maintainer-only spec comparison lives in tools/openapi_audit.py.

cmake_minimum_required(VERSION 3.28)

function(validate_openapi_manifest MANIFEST_JSON OUT_OK OUT_REPORT OUT_TOTAL OUT_IMPLEMENTED)
  set(_problems "")
  set(_total 0)
  set(_implemented 0)
  # Family owners listed under the portfolio issue (#36). A specific child
  # ticket may refine one row, but the manifest keeps every planned operation
  # attached to the durable family that owns its completion.
  set(_family_issues 10 39 40 41 42 43 44 45 46 47 48 49)

  string(JSON _root_type ERROR_VARIABLE _err TYPE "${MANIFEST_JSON}")
  if(NOT _err STREQUAL "NOTFOUND" OR NOT _root_type STREQUAL "OBJECT")
    set(${OUT_OK} FALSE PARENT_SCOPE)
    set(${OUT_REPORT} "manifest root is not a JSON object: ${_err}" PARENT_SCOPE)
    set(${OUT_TOTAL} 0 PARENT_SCOPE)
    set(${OUT_IMPLEMENTED} 0 PARENT_SCOPE)
    return()
  endif()

  string(JSON _schema ERROR_VARIABLE _err GET "${MANIFEST_JSON}" schema_version)
  if(NOT _err STREQUAL "NOTFOUND" OR NOT _schema STREQUAL "1")
    string(APPEND _problems "\n  schema_version must be 1")
  endif()

  foreach(_field url repository_url version sha256 audited_on)
    string(JSON _value ERROR_VARIABLE _err GET "${MANIFEST_JSON}" source ${_field})
    if(NOT _err STREQUAL "NOTFOUND" OR _value STREQUAL "")
      string(APPEND _problems "\n  source.${_field} is required and must be non-empty")
    endif()
  endforeach()
  string(JSON _sha ERROR_VARIABLE _err GET "${MANIFEST_JSON}" source sha256)
  string(LENGTH "${_sha}" _sha_length)
  if(_err STREQUAL "NOTFOUND" AND (NOT _sha_length EQUAL 64 OR NOT _sha MATCHES "^[0-9a-f]+$"))
    string(APPEND _problems "\n  source.sha256 must be 64 lowercase hexadecimal characters")
  endif()

  string(JSON _operations_type ERROR_VARIABLE _err TYPE "${MANIFEST_JSON}" operations)
  if(NOT _err STREQUAL "NOTFOUND" OR NOT _operations_type STREQUAL "ARRAY")
    string(APPEND _problems "\n  operations is required and must be an array")
  else()
    string(JSON _total LENGTH "${MANIFEST_JSON}" operations)
  endif()

  set(_seen "")
  if(_total GREATER 0)
    math(EXPR _last "${_total} - 1")
    foreach(_i RANGE 0 ${_last})
      set(_prefix "operations[${_i}]")
      foreach(_field method path family state security request_media response_media)
        string(JSON _type ERROR_VARIABLE _err TYPE "${MANIFEST_JSON}" operations ${_i} ${_field})
        if(NOT _err STREQUAL "NOTFOUND")
          string(APPEND _problems "\n  ${_prefix}.${_field} is required")
        endif()
      endforeach()

      string(JSON _method ERROR_VARIABLE _method_err GET "${MANIFEST_JSON}" operations ${_i} method)
      string(JSON _path ERROR_VARIABLE _path_err GET "${MANIFEST_JSON}" operations ${_i} path)
      string(JSON _family ERROR_VARIABLE _family_err GET "${MANIFEST_JSON}" operations ${_i} family)
      string(JSON _state ERROR_VARIABLE _state_err GET "${MANIFEST_JSON}" operations ${_i} state)

      if(_method_err STREQUAL "NOTFOUND" AND NOT _method MATCHES "^(GET|POST|PUT|PATCH|DELETE|OPTIONS|HEAD|TRACE)$")
        string(APPEND _problems "\n  ${_prefix}.method '${_method}' is not a supported HTTP method")
      endif()
      if(_path_err STREQUAL "NOTFOUND" AND NOT _path MATCHES "^/")
        string(APPEND _problems "\n  ${_prefix}.path must start with '/'")
      endif()
      if(_family_err STREQUAL "NOTFOUND" AND _family STREQUAL "")
        string(APPEND _problems "\n  ${_prefix}.family must be non-empty")
      endif()
      if(_state_err STREQUAL "NOTFOUND" AND NOT _state MATCHES "^(implemented|planned|unsupported)$")
        string(APPEND _problems "\n  ${_prefix}.state '${_state}' is unknown")
      endif()

      if(_method_err STREQUAL "NOTFOUND" AND _path_err STREQUAL "NOTFOUND")
        set(_key "${_method} ${_path}")
        if(_key IN_LIST _seen)
          string(APPEND _problems "\n  duplicate operation ${_key}")
        else()
          list(APPEND _seen "${_key}")
        endif()
      endif()

      string(JSON _security_type ERROR_VARIABLE _err TYPE "${MANIFEST_JSON}" operations ${_i} security)
      if(_err STREQUAL "NOTFOUND" AND NOT _security_type STREQUAL "ARRAY")
        string(APPEND _problems "\n  ${_prefix}.security must be an array")
      endif()
      string(JSON _request_type ERROR_VARIABLE _err TYPE "${MANIFEST_JSON}" operations ${_i} request_media)
      if(_err STREQUAL "NOTFOUND" AND NOT _request_type STREQUAL "ARRAY")
        string(APPEND _problems "\n  ${_prefix}.request_media must be an array")
      endif()
      string(JSON _response_type ERROR_VARIABLE _err TYPE "${MANIFEST_JSON}" operations ${_i} response_media)
      if(_err STREQUAL "NOTFOUND" AND NOT _response_type STREQUAL "OBJECT")
        string(APPEND _problems "\n  ${_prefix}.response_media must be an object keyed by response status")
      endif()

      if(_state STREQUAL "implemented")
        math(EXPR _implemented "${_implemented} + 1")
        string(JSON _public_type ERROR_VARIABLE _err TYPE "${MANIFEST_JSON}" operations ${_i} public_api)
        if(NOT _err STREQUAL "NOTFOUND" OR NOT _public_type STREQUAL "ARRAY")
          string(APPEND _problems "\n  ${_prefix}.public_api is required for an implemented operation")
        else()
          string(JSON _public_len LENGTH "${MANIFEST_JSON}" operations ${_i} public_api)
          if(_public_len EQUAL 0)
            string(APPEND _problems "\n  ${_prefix}.public_api must name at least one public method")
          endif()
        endif()
      elseif(_state MATCHES "^(planned|unsupported)$")
        string(JSON _issue_type ERROR_VARIABLE _err TYPE "${MANIFEST_JSON}" operations ${_i} tracking_issue)
        if(NOT _err STREQUAL "NOTFOUND" OR NOT _issue_type STREQUAL "NUMBER")
          string(APPEND _problems "\n  ${_prefix}.tracking_issue is required for state '${_state}'")
        else()
          string(JSON _issue GET "${MANIFEST_JSON}" operations ${_i} tracking_issue)
          if(_issue LESS 1)
            string(APPEND _problems "\n  ${_prefix}.tracking_issue must be a positive issue number")
          elseif(NOT _issue IN_LIST _family_issues)
            string(APPEND _problems "\n  ${_prefix}.tracking_issue #${_issue} is not a family issue under #36")
          endif()
        endif()
      endif()
    endforeach()
  endif()

  if(_problems STREQUAL "")
    set(_ok TRUE)
    set(_report "${_implemented}/${_total} operations implemented")
  else()
    set(_ok FALSE)
    set(_report "manifest validation failed:${_problems}")
  endif()
  set(${OUT_OK} ${_ok} PARENT_SCOPE)
  set(${OUT_REPORT} "${_report}" PARENT_SCOPE)
  set(${OUT_TOTAL} ${_total} PARENT_SCOPE)
  set(${OUT_IMPLEMENTED} ${_implemented} PARENT_SCOPE)
endfunction()

function(validate_openapi_coverage_text TEXT EXPECTED OUT_OK)
  string(FIND "${TEXT}" "${EXPECTED}" _found)
  if(_found EQUAL -1)
    set(${OUT_OK} FALSE PARENT_SCOPE)
  else()
    set(${OUT_OK} TRUE PARENT_SCOPE)
  endif()
endfunction()
